export { default as Section1Temporary } from "./Section1Temporary"
export { default as Section1Init } from "./Section1Init"
export { default as Section2Marquee } from "./Section2Marquee"
export { default as Section3Projects } from "./Section3Projects"
export { default as Section4AboutSkill } from "./Section4AboutSkill"
export { default as Section5Contact } from "./Section5Contac"
