export { default as Hero } from "./Hero/index"
export { default as Marquee } from "./Marquee/index"
export { default as About } from "./About/index"
export { default as Projects } from "./Projects/index"
export { default as ProjectsPage } from "./Projects/Page/index"
export { default as Skills } from "./Skills/index"
export { default as Contact } from "./Contact/index"
