export { default as Section1Temporary } from "./Section1Temporary"
export { default as Section1Init } from "./Section1Init"
export { default as Section2Marquee } from "./Section2Marquee"
export { default as Section3About } from "./Section3About"
export { default as Section4Projects } from "./Section4Projects"
export { default as Section5Skills } from "./Section5Skills"
export { default as Section6Contact } from "./Section6Contac"
